name: tracx
description: "A new Flutter project."
publish_to: "none"

version: 1.0.7+7

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  excel: ^4.0.6 

  # Ícones do iOS
  cupertino_icons: ^1.0.8

  # Dependências normais
  intl: ^0.20.2
  mobile_scanner: ^3.5.4
  json_annotation: ^4.8.0
  uuid: ^4.5.1
  share_plus: ^11.0.0
  path_provider: ^2.1.2
  http: ^1.4.0
  shared_preferences: ^2.0.15
  webdav_client: ^1.0.0
  printing: ^5.14.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  win32: ^5.14.0
  pdf: ^3.10.7
  flutter_zxing: ^2.2.1
  sqflite: ^2.4.2
  permission_handler: ^12.0.1
  rename: ^3.1.0
  flutter_datawedge: ^3.2.0
  connectivity_plus: ^7.0.0
  syncfusion_flutter_gauges: ^32.1.21
  dio: ^5.9.0 
  install_plugin_v3: ^ 3.1.3
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  shimmer: ^3.0.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_native_splash: ^2.3.11
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/tracx_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo_splash.png
    - assets/logo_login.png
    - assets/logo_icon.png
    - assets/ic_launcher.png
    - assets/logo2.png
